name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install huggingface_hub
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Upload folder to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - << 'PY'
          import os
          from huggingface_hub import HfApi, upload_folder, create_repo, hf_hub_url

          token = os.environ["HF_TOKEN"]
          repo_id = "0v0paco/ColorvideoSubs"        # <- your Space name without "spaces/"
          api = HfApi(token=token)

          # Ensure Space exists as a Space repo (sdk=gradio is read from README)
          try:
            create_repo(repo_id=repo_id, token=token, repo_type="space", exist_ok=True)
          except Exception:
            pass

          # Push everything except CI and git internals
          upload_folder(
              folder_path=".",
              repo_id=repo_id,
              repo_type="space",
              commit_message="Auto-deploy from GitHub Actions",
              ignore_patterns=[
                ".git/*", ".git*", ".github/*", "__pycache__/*", "*.pyc",
                "venv/*", ".venv/*", ".DS_Store"
              ]
          )
          print("Uploaded. Space URL:", hf_hub_url(repo_id=repo_id, filename="", repo_type="space"))
          PY
